environment:
  matrix:
    - nodejs_version: "5.9.1"
      ADDON_VERSION: "47"

platform:
  - x64

install:
  - echo %ADDON_VERSION%
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node -v
  - npm install

build: off

test_script:
  - npm test
