environment:
  matrix:
    - nodejs_version: "5.12.0"
      ADDON_VERSION: "47"

platform:
  - x64

install:
  - echo %ADDON_VERSION%
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node -v
  - npm install -g npm
  - npm install -g nw-gyp node-pre-gyp
  - npm install
