environment:
  matrix:
    - nodejs_version: "6.6.0"
      ADDON_VERSION: "47"

platform:
  - x64

install:
  - echo %ADDON_VERSION%
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node -v
  - npm install

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
